module.exports = {
  projects: [
    '<rootDir>/apps/example-app',
    '<rootDir>/apps/api',
    '<rootDir>/libs/core',
    '<rootDir>/libs/typeorm',
    '<rootDir>/libs/angular',
    '<rootDir>/libs/common',
    '<rootDir>/libs/testing',
    '<rootDir>/apps/todo-example-app',
    '<rootDir>/libs/todo-example-app/server/core/services',
    '<rootDir>/libs/todo-example-app/server/core/domain',
    '<rootDir>/libs/todo-example-app/server/orcha',
    '<rootDir>/libs/todo-example-app/client/shared/data-access',
    '<rootDir>/libs/todo-example-app/client/shell',
    '<rootDir>/libs/todo-example-app/shared/domain',
    '<rootDir>/libs/todo-example-app/shared/util',
    '<rootDir>/libs/todo-example-app/client/shared/util',
  ],
};
