import { createQuery } from './create-query';
import { parseQuery } from './transform';

describe('parseQuery', () => {
  const data = {
    id: '5hslucwJtLmsuKp1CaHhC',
    email: 'a@a.com',
    superAdmin: false,
    admin: false,
    active: true,
    dateCreated: '2022-08-23T17:52:38.572Z',
    dateLastLoggedIn: '2022-08-23T17:52:38.572Z',
    role: 'client',
    reporter: {
      id: 'NZWDHtzf0wGjXmtF94ykq',
      allowedSnf: [],
      snfPermissionsType: 'selected',
      dateCreated: '2022-08-23T17:52:38.572Z',
      user: {
        id: '5hslucwJtLmsuKp1CaHhC',
        comments: [],
        history: [],
        caseNotifications: [],
        theme: 'light',
        savedCaseColumns: [],
        email: 'a@a.com',
        passwordHash: '',
        salt: '',
        superAdmin: false,
        admin: false,
        active: true,
        dateUpdated: '2022-08-23T17:52:38.572Z',
        dateCreated: '2022-08-23T17:52:38.572Z',
        dateLastLoggedIn: '2022-08-23T17:52:38.572Z',
        role: 'client',
        caseworker: {
          id: 'WcF5VY1_ZojG9IetfzTw3',
          cases: [],
          dateCreated: '2022-08-23T17:52:38.572Z',
          user: {
            id: '5hslucwJtLmsuKp1CaHhC',
            comments: [],
            history: [],
            caseNotifications: [],
            theme: 'light',
            savedCaseColumns: [],
            email: 'a@a.com',
            passwordHash: '',
            salt: '',
            superAdmin: false,
            admin: false,
            active: true,
            dateUpdated: '2022-08-23T17:52:38.572Z',
            dateCreated: '2022-08-23T17:52:38.572Z',
            dateLastLoggedIn: '2022-08-23T17:52:38.572Z',
            role: 'client',
            client: {
              id: 'oeK5FNLjtrPxKhmR9qG_0',
              dateCreated: '2022-08-23T17:52:38.572Z',
              allowedCases: [],
              user: {
                id: '5hslucwJtLmsuKp1CaHhC',
                comments: [],
                history: [],
                caseNotifications: [],
                theme: 'light',
                savedCaseColumns: [],
                email: 'a@a.com',
                passwordHash: '',
                salt: '',
                superAdmin: false,
                admin: false,
                active: true,
                dateUpdated: '2022-08-23T17:52:38.572Z',
                dateCreated: '2022-08-23T17:52:38.572Z',
                dateLastLoggedIn: '2022-08-23T17:52:38.572Z',
                role: 'client',
              },
            },
          },
        },
        client: {
          id: 'oeK5FNLjtrPxKhmR9qG_0',
          dateCreated: '2022-08-23T17:52:38.572Z',
          allowedCases: [],
          user: {
            id: '5hslucwJtLmsuKp1CaHhC',
            comments: [],
            history: [],
            caseNotifications: [],
            theme: 'light',
            savedCaseColumns: [],
            email: 'a@a.com',
            passwordHash: '',
            salt: '',
            superAdmin: false,
            admin: false,
            active: true,
            dateUpdated: '2022-08-23T17:52:38.572Z',
            dateCreated: '2022-08-23T17:52:38.572Z',
            dateLastLoggedIn: '2022-08-23T17:52:38.572Z',
            role: 'client',
            caseworker: {
              id: 'WcF5VY1_ZojG9IetfzTw3',
              cases: [],
              dateCreated: '2022-08-23T17:52:38.572Z',
              user: {
                id: '5hslucwJtLmsuKp1CaHhC',
                comments: [],
                history: [],
                caseNotifications: [],
                theme: 'light',
                savedCaseColumns: [],
                email: 'a@a.com',
                passwordHash: '',
                salt: '',
                superAdmin: false,
                admin: false,
                active: true,
                dateUpdated: '2022-08-23T17:52:38.572Z',
                dateCreated: '2022-08-23T17:52:38.572Z',
                dateLastLoggedIn: '2022-08-23T17:52:38.572Z',
                role: 'client',
              },
            },
          },
        },
      },
    },
    client: {
      id: 'oeK5FNLjtrPxKhmR9qG_0',
      dateCreated: '2022-08-23T17:52:38.572Z',
      allowedCases: [],
      user: {
        id: '5hslucwJtLmsuKp1CaHhC',
        comments: [],
        history: [],
        caseNotifications: [],
        theme: 'light',
        savedCaseColumns: [],
        email: 'a@a.com',
        passwordHash: '',
        salt: '',
        superAdmin: false,
        admin: false,
        active: true,
        dateUpdated: '2022-08-23T17:52:38.572Z',
        dateCreated: '2022-08-23T17:52:38.572Z',
        dateLastLoggedIn: '2022-08-23T17:52:38.572Z',
        role: 'client',
        caseworker: {
          id: 'WcF5VY1_ZojG9IetfzTw3',
          cases: [],
          dateCreated: '2022-08-23T17:52:38.572Z',
          user: {
            id: '5hslucwJtLmsuKp1CaHhC',
            comments: [],
            history: [],
            caseNotifications: [],
            theme: 'light',
            savedCaseColumns: [],
            email: 'a@a.com',
            passwordHash: '',
            salt: '',
            superAdmin: false,
            admin: false,
            active: true,
            dateUpdated: '2022-08-23T17:52:38.572Z',
            dateCreated: '2022-08-23T17:52:38.572Z',
            dateLastLoggedIn: '2022-08-23T17:52:38.572Z',
            role: 'client',
            reporter: {
              id: 'NZWDHtzf0wGjXmtF94ykq',
              allowedSnf: [],
              snfPermissionsType: 'selected',
              dateCreated: '2022-08-23T17:52:38.572Z',
              user: {
                id: '5hslucwJtLmsuKp1CaHhC',
                comments: [],
                history: [],
                caseNotifications: [],
                theme: 'light',
                savedCaseColumns: [],
                email: 'a@a.com',
                passwordHash: '',
                salt: '',
                superAdmin: false,
                admin: false,
                active: true,
                dateUpdated: '2022-08-23T17:52:38.572Z',
                dateCreated: '2022-08-23T17:52:38.572Z',
                dateLastLoggedIn: '2022-08-23T17:52:38.572Z',
                role: 'client',
              },
            },
          },
        },
        reporter: {
          id: 'NZWDHtzf0wGjXmtF94ykq',
          allowedSnf: [],
          snfPermissionsType: 'selected',
          dateCreated: '2022-08-23T17:52:38.572Z',
          user: {
            id: '5hslucwJtLmsuKp1CaHhC',
            comments: [],
            history: [],
            caseNotifications: [],
            theme: 'light',
            savedCaseColumns: [],
            email: 'a@a.com',
            passwordHash: '',
            salt: '',
            superAdmin: false,
            admin: false,
            active: true,
            dateUpdated: '2022-08-23T17:52:38.572Z',
            dateCreated: '2022-08-23T17:52:38.572Z',
            dateLastLoggedIn: '2022-08-23T17:52:38.572Z',
            role: 'client',
            caseworker: {
              id: 'WcF5VY1_ZojG9IetfzTw3',
              cases: [],
              dateCreated: '2022-08-23T17:52:38.572Z',
              user: {
                id: '5hslucwJtLmsuKp1CaHhC',
                comments: [],
                history: [],
                caseNotifications: [],
                theme: 'light',
                savedCaseColumns: [],
                email: 'a@a.com',
                passwordHash: '',
                salt: '',
                superAdmin: false,
                admin: false,
                active: true,
                dateUpdated: '2022-08-23T17:52:38.572Z',
                dateCreated: '2022-08-23T17:52:38.572Z',
                dateLastLoggedIn: '2022-08-23T17:52:38.572Z',
                role: 'client',
              },
            },
          },
        },
      },
    },
  };

  const UserForAdminQueryModel = createQuery<any>()({
    profile: true,
    email: true,
    role: true,
    active: true,
    admin: true,
    superAdmin: true,
    dateCreated: true,
    dateLastLoggedIn: true,
    reporter: { allowedSnf: { snf: {} }, snfPermissionsType: true },
    client: { allowedCases: { case: {}, viewOrEdit: true } },
  });

  it('parse', () => {
    expect(parseQuery<any, any>(data, UserForAdminQueryModel)).toStrictEqual({
      id: '5hslucwJtLmsuKp1CaHhC',
      email: 'a@a.com',
      role: 'client',
      admin: false,
      active: true,
      superAdmin: false,
      dateCreated: '2022-08-23T17:52:38.572Z',
      dateLastLoggedIn: '2022-08-23T17:52:38.572Z',
      reporter: {
        id: 'NZWDHtzf0wGjXmtF94ykq',
        allowedSnf: [],
        snfPermissionsType: 'selected',
      },
      client: {
        id: 'oeK5FNLjtrPxKhmR9qG_0',
        allowedCases: [],
      },
    });
  });
});
